on:
  release:
    types:
    - released

jobs:
  publish-opam-package:
    uses: ./.github/workflows/publish-opam-package.yml
    with:
      tag: ${{ github.event.release.tag_name }}
      prerelease: ${{ github.event.release.prerelease }}
    secrets: inherit
